// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC63VckDRUJ5gF05p66tuoPaqj11AZ0L0',
    appId: '1:790450380898:web:90772c86e42d7fe0dd313b',
    messagingSenderId: '790450380898',
    projectId: 'geolocation-533df',
    authDomain: 'geolocation-533df.firebaseapp.com',
    storageBucket: 'geolocation-533df.appspot.com',
    measurementId: 'G-WDQVXHYR3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd2stX6p5KljjqPau-D365HzfBrgWSD_k',
    appId: '1:790450380898:android:85e81fbf6688b5fddd313b',
    messagingSenderId: '790450380898',
    projectId: 'geolocation-533df',
    storageBucket: 'geolocation-533df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQhBVLxAw06BaxE71Mfp-OerisSCGctu0',
    appId: '1:790450380898:ios:6540f0e83aa8e63edd313b',
    messagingSenderId: '790450380898',
    projectId: 'geolocation-533df',
    storageBucket: 'geolocation-533df.appspot.com',
    iosBundleId: 'com.example.geol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQhBVLxAw06BaxE71Mfp-OerisSCGctu0',
    appId: '1:790450380898:ios:45266b3f0b2096c8dd313b',
    messagingSenderId: '790450380898',
    projectId: 'geolocation-533df',
    storageBucket: 'geolocation-533df.appspot.com',
    iosBundleId: 'com.example.geol.RunnerTests',
  );
}
